module.exports = {
    SERVICES: {
      ALERT: 'alertService',
      STRUCTURE: 'structureService',
      LOCATION_HISTORY: 'locationHistoryService',
      JOBS: 'jobsService',
      SCRIPTS: 'scriptsService',
      GITLAB: 'gitLabService',
      NODES: 'nodesService',
      EMAILS: 'mailsService',
      CLIENTS: 'clientsService',
      COMPANIES: 'companiesService',
      BATTERIES: 'batteriesService',
      NODE_SESSION_FRAMES_SERVICE: 'nodeSessionFramesService',
      NODE_SESSIONS_SERVICE: 'nodeSessionsService',
      NODE_MANAGER: 'nodesManagerService',
      NODE_STATUSES: 'nodeStatusesService',
      NETWORK_MANAGER_SERVICE: 'networkManagerService',
      NETWORK_CONNECTION_SERVICE: 'networkConnectionsService',
      NETWORK_SESSION: 'networkSessionsService',
      NETWORK_USAGE: 'networkUsageService',
      AUTHENTICATION: 'authenticationsService',
      BATTERY_MODEL: 'batteryModelsService',
      ERRORS: 'errorsService',
      APPLICATIONS: 'applicationsService',
      SIMS: 'simService',
      PLUGINS: 'pluginsService',
      ADDRESS: 'addressesService',
      GEOCODE: 'geoCodeService',
      APITOKEN: 'apiTokenService',
      USERS: 'usersService',
      FIFO: 'fifosService',
      FIRMWARES: 'firmwaresService',
      GATEWAYS: 'gatewaysService',
      GATEWAYSMANAGER: 'gatewayManagerService',
      GATEWAYSESSION: 'gatewaySessionsService',
      OTAS: 'otasService',
      LORA_EVENTS: 'loraEventsService',
      LORA_MANAGER: 'loraManagerService',
      LORA_NETWORKS: 'loraNetworksService',
      LORA_FRAMES: 'loraFramesService',
      LORA_MISSINGINDEX: 'loraMissingIndexService',
      MQTT: 'mqttService',
      ACTIVE_SESSION: 'activeSessionManagerService',
      PLUGINS_MANAGER: 'pluginsManagerService',
      APIS: 'apisService',
      TIMEZONES: 'timezonesService',
      APPLICATIONS_SYNC_HISTORY: 'applicationsSyncHistoryServices',
      TICKETS: 'ticketsService',
      TICKET_COMMENTS: 'ticketCommentsService',
      CONNECTORS: 'connectorsService'
    },
    HELPERS: {
      DAL_COMMON: 'dalCommon',
      BUSINESS_COMMON: 'businessCommon',
      CONFIG: 'config',
      CONSTANTS: 'constants',
      UTILS: 'utils',
      ROOT_DIR: __dirname
    },
    LOGS: {
      MAIN_LOG: 'mainLog',
      PLUGIN_LOG: 'pluginLog',
      API_LOG: 'apiLog',
      APPLICATION_LOG: 'applicationLog'
    },
    LIBRARIES: {
      LIVEMODULE_MANAGER: 'liveModuleManager',
      DATE: 'Date'
    },
    API: {
      BATTERY_MODEL: 'batterymodel',
      LOCATION_HISTORY: 'locationhistory',
      STRUCTURE: 'structures',
      ALERT: 'alerts'
    }
  };